name: Test and Deploy

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
      - run: npm ci
      - run: npm test
      
  deploy:
    name: Deploy to Railway
    runs-on: ubuntu-latest
    needs: ["test"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
      - run: npm install
      - run: npm test
      - name: Install Railway
        run: npm i -g @railway/cli
      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  migrate:
    name: Run production migrations
    runs-on: ubuntu-latest
    needs: ["deploy"]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: 'npm'
      - run: npm install
      - name: Run prisma migrations
        run: npx prisma migrate deploy
        env:
           DATABASE_URL: ${{ secrets.DATABASE_URL }}
